/**
 * Available song tags
 */
export enum Tags {
  Adoration = 'adoration',
  Assurance = 'assurance',
  Beauty = 'beauty',
  Blessing = 'blessing',
  Celebration = 'celebration',
  Children = 'children',
  Christmas = 'christmas',
  Comfort = 'comfort',
  Commitment = 'commitment',
  Communion = 'communion',
  Creation = 'creation',
  Cross = 'cross',
  Declaration = 'declaration',
  Desire = 'desire',
  Easter = 'easter',
  Encouragement = 'encouragement',
  Evangelism = 'evangelism',
  Faith = 'faith',
  Faithfulness = 'faithfulness',
  Father = 'father',
  Forgiveness = 'forgiveness',
  Freedom = 'freedom',
  Glory = 'glory',
  Grace = 'grace',
  Greatness = 'greatness',
  Guidance = 'guidance',
  Healing = 'healing',
  Holiness = 'holiness',
  HolySpirit = 'holyspirit',
  Hope = 'hope',
  Humility = 'humility',
  Jesus = 'jesus',
  Joy = 'joy',
  Kingship = 'kingship',
  Life = 'life',
  Light = 'light',
  Longing = 'longing',
  Love = 'love',
  Obedience = 'obedience',
  Peace = 'peace',
  Petition = 'petition',
  Power = 'power',
  Praise = 'praise',
  Prayer = 'prayer',
  Presence = 'presence',
  Rest = 'rest',
  Resurrection = 'resurrection',
  Revival = 'revival',
  Sacrifice = 'sacrifice',
  Salvation = 'salvation',
  Strength = 'strength',
  Surrender = 'surrender',
  Thankfulness = 'thankfulness',
  Trust = 'trust',
  Truth = 'truth',
  Unity = 'unity',
  Victory = 'victory',
  Worship = 'worship',
}

/**
 * Available song languges
 */
export enum SongLanguages {
  DE = 'de',
  EN = 'en',
  FR = 'fr',
  LI = 'li',
}
